version: ""

formatter: markdown table

name:  terraform-aws-iam-role-vmimport

content: |-
  # terraform-aws-iam-role-vmimport

  GitHub: [StratusGrid/terraform-aws-iam-role-vmimport](https://github.com/StratusGrid/terraform-aws-iam-role-vmimport)

  This module configures an AWS account with with an iam role to facilitate vm imports with vm import/export service, using an existing import bucket.
  
  ## Example Usage:
  ```hcl
  {{ include "examples/example1.tfnot" }}
  ```
  ---

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  ---

  <span style="color:red">Note:</span> Manual changes to the README will be overwritten when the documentation is updated. To update the documentation, run `terraform-docs -c .config/.terraform-docs.yml .`

sections:
  show:
    - resources
    - inputs
    - outputs
    - providers
    - requirements

sort:
  enabled: true
  by: name

output:
  file: README.md
  mode: replace
